name: 'Image size'
description: 'Record size of docker image'
inputs:
  image-name:  # id of input
    description: 'Name of image'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps: 
    - run: env
      shell: bash
    - run: docker images ${{ inputs.image-name }}
      shell: bash
